// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Infrastructure.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(BlogDBContext))]
    [Migration("20230823022020_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Server.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            Content = "This is post #1 and it has some very interesting content.",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostID = 2,
                            Content = "This is post #2 and it has some very interesting content.",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostID = 3,
                            Content = "This is post #3 and it has some very interesting content.",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostID = 4,
                            Content = "This is post #4 and it has some very interesting content.",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostID = 5,
                            Content = "This is post #5 and it has some very interesting content.",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostID = 6,
                            Content = "This is post #6 and it has some very interesting content.",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
